### ISSUE TITLE
statik -> statikAdapter?

### ISSUE THREAD

**Issue by beylerian** [kittinunf/Statik#70]
### About

Would it look better to write `statikAdapter` or just `adapter` instead of `statik` when defining the actual adapter?

So for example instead of 

```kotlin
statikAdapter = statik {
    sections(s1, s2, s3, s4)
}
```

we would have something like

```kotlin
adapter = statikAdapter {
    sections(s1, s2, s3, s4)
}
```

or 

```kotlin
adapter = adapter {
    sections(s1, s2, s3, s4)
}
```

**Comment by kittinunf** [comment]
I think it is a reasonable change. Let's do it.
